### ISSUE TITLE
SM2是密钥交换，不是具体算法，建议换个名字

### ISSUE THREAD

**Issue by Le0nFisher** [wechat-miniprogram/sm-crypto#11]

**Comment by JuneAndGreen** [comment]
密钥交换协议是其中一部分。参考自：https://github.com/JuneAndGreen/sm-crypto/blob/master/docs/SM2%E6%A4%AD%E5%9C%86%E6%9B%B2%E7%BA%BF%E5%85%AC%E9%92%A5%E5%AF%86%E7%A0%81%E7%AE%97%E6%B3%95.pdf

![image](https://user-images.githubusercontent.com/7931744/68034954-a49a1e80-fcfd-11e9-83f7-0cf0013acd98.png)
