### ISSUE TITLE
sm4 下，padding：‘none’,无返回数据

### ISSUE THREAD

**Issue by hyucheng** [wechat-miniprogram/sm-crypto#17]
调用情况如下图：
![image](https://user-images.githubusercontent.com/32702840/97145940-015dd700-17a2-11eb-941d-a64233035e24.png)

输出情况如下图：
![image](https://user-images.githubusercontent.com/32702840/97145902-ec814380-17a1-11eb-80cd-bf6815cbfa3e.png)

**Comment by JuneAndGreen** [comment]
无填充模式按16字节一个单位算，少于16个字节的会被丢弃。建议传字符串就走默认填充，想自己实现填充或者不填充（注意16个字节一单位的切割方式），那就传字节数组吧。
