### ISSUE TITLE
hexToArray 这个方法 对于hex是奇数的情况 是 有bug的

### ISSUE THREAD

**Issue by xichen744** [wechat-miniprogram/sm-crypto#2]
建议在 头部添加以下代码
  if ((hexStr.length % 2) !== 0) {
    hexStr = leftPad(hexStr, hexStr.length + 1)
  }

**Comment by JuneAndGreen** [comment]
感谢反馈。之前的用例传进来的都是偶数位，所以一直没有踩到这个坑。已在 0.0.5 fixed。
