### ISSUE TITLE
sm2重构后签名问题

### ISSUE THREAD

**Issue by YS-zhusy** [wechat-miniprogram/sm-crypto#20]
sm2重构后新老代码做的签名不能相互验签成功,是算法逻辑变了吗

**Comment by JuneAndGreen** [comment]
没有更换算法逻辑，只是换了部分实现。签名这块主逻辑没动，只替换了 sm3 的 hash 实现和 asn.1 der 编码的实现。

我试了下 0.2.7 和 0.3.0 的对比，在所有测试用例中，无论是 0.2.7 签名、0.3.0 验签，还是 0.3.0 签名、0.2.7 验签都没有问题。可以检查一下调用参数之类的是否有不同，也可以试试切回旧版本是否就正常了。如果怎么都没排查出问题的话，看看能不能提供一个问题 demo 给我试试。

**Comment by YS-zhusy** [comment]
@六月与格林 你好,是这样的,sm2签名的时候,当userId的长度超过31位时,新旧版本就会相互校验通不过
![1627288667(1)](https://user-images.githubusercontent.com/44077832/126959965-7ea889db-1e65-491a-9074-f52f7e053c67.png)

**Comment by JuneAndGreen** [comment]
fixed：miniprogram-sm-crypto@0.3.2
