### ISSUE TITLE
生成roundkey算法是不是有问题

### ISSUE THREAD

**Issue by pecliu** [wechat-miniprogram/sm-crypto#3]
https://github.com/wechat-miniprogram/sm-crypto/blob/c66b20d9c414c0a2cde2b4a4e15e5ff44b27c39f/src/sm4/index.js#L119

**Comment by JuneAndGreen** [comment]
请问这个地方有什么问题呢？

**Comment by pecliu** [comment]
是我没有阅读仔细，此处x[0]已经变成了K4，不好意思，请关闭issue吧
