### ISSUE TITLE
想使用sm2的getPublicKeyFromPrivateKey

### ISSUE THREAD

**Issue by cliu717** [wechat-miniprogram/sm-crypto#40]
您好，我想通过SM2的私钥生成对应的公钥，我看到你们的库里有getPublicKeyFromPrivateKey这个函数，但是这个函数没有加入到exports里，请问可以把这个函数加入嘛。或者说有没有其他办法让我调用这个函数。谢谢

**Comment by JuneAndGreen** [comment]
sm-crypto@0.3.13 已支持
