### ISSUE TITLE
预览时报错了

### ISSUE THREAD

**Issue by acmilank22** [wechat-miniprogram/sm-crypto#5]
<img width="278" alt="WX20190402-160406@2x" src="https://user-images.githubusercontent.com/12584040/55386024-18eec280-5561-11e9-8064-8f94953a41ed.png">

用扫描二维码预览 ide会假死
用自动预览 就可以看到错误信息了

**Comment by lihaiJett** [comment]
我也遇到了，是代码保护的问题

**Comment by JuneAndGreen** [comment]
![image](https://user-images.githubusercontent.com/7931744/61815018-e5bba080-ae7b-11e9-81e3-ee655745ffe5.png)
去掉这个试试？
