### ISSUE TITLE
sm4下的encrypt会发生位数丢失

### ISSUE THREAD

**Issue by johnzhu12** [wechat-miniprogram/sm-crypto#7]
sm4/index.js下的sm4方法用来加密，看到第148行判断
```js
while(inLen >= BLOCK) //BLOCK = 16
```
当文件的ArrayBuffer对16取余如果有余数的话，最后几位会被丢弃。（比如加密pdf最后的EOF一行会丢失）
在业务里补了几位0解决，比如余数为11，我就补了5位0，然后解密之后再把5位0去除。
希望作者能在sm4的代码里把padding情况加上

**Comment by l1t1** [comment]
谢谢，我这么处理的
//长度填充为16的倍数
len=ss.length
n=len%16
ss+=new Array(n+1).join("\0")

**Comment by JuneAndGreen** [comment]
已默认支持 pkcs#5 填充，可参考 readme 或者 sm4.test.js 测试用例。
